config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: %i[new create index show]
  devise_for :users, controllers: { registrations: 'registrations'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 5 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, :email, presence: true, uniqueness: true
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body, :user_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
private

 def sign_up_params
   params.require(:user).permit( :username, :email, :password, :password_confirmation)
 end

 def account_update_params
   params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.1/css/bulma.min.css' %>
  </head>
  <body>
    <% if flash[:notice] %>
      <div class='notification is-primary global-notification'>
        <p class='notice'><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class='notification is-danger global-notification'>
        <p class='alert'><%= alert %></p>
      </div>
    <% end %>
    <nav class='navbar' role='navigation' aria-label='main navigation'>
      <div class='navbar-brand'>
        <%= link_to root_path, class: 'navbar-item' do %>
          <h1 class='title is-5'>Members Only</h1>
        <% end %>
        <div role ='button' class='navbar-burger' data-target='navbarExample'>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div id='navbarExample' class='navbar-menu'>
        <div class='navbar-end'>
          <% if user_signed_in? %>
            <p class='navbar-item'><%= link_to current_user.username, edit_user_registration_path %></p>
            <p class='navbar-item'><%= link_to 'Logout', destroy_user_session_path, method: :delete %></p>
          <% else %>
            <p class='navbar-item'><%= link_to 'Sign up', new_user_registration_path %></p>
            <p class='navbar-item'><%= link_to 'Sign in', new_user_session_path %></p>
          <% end %>
        </div>
      </div>
    </nav>
    <hr class='nav-hr'>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<section class='section pt-1 pb-5'>
  <div class='container'>
    <div class='columns is-centered'>
      <div class='column is-4'>
        <%= form_with(model: post) do |form| %>
          <% if post.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
              <ul>
                <% post.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field">
            <div class='control'>
              <%= form.label :title, class: 'label' %>
              <%= form.text_field :title, class: 'input' %>
            </div>
          </div>
          <div class="field">
            <%= form.label :body, class: 'label' %>
            <%= form.text_area :body, class: 'textarea'%>
          </div>
          <div class="actions">
            <%= form.submit 'Create Post', class: 'button is-medium'%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h2 class='has-text-centered title is-4'>
  <% if user_signed_in? %>
    Displaying all Posts
  <% else%>
    Log in to see who posted!
  <% end %>
</h2>
<br>
<% if user_signed_in? %>
  <div class='columns is-centered'>
    <div class='column has-text-centered'>
      <%= link_to 'New Post', new_post_path, class: 'button is-link'  %>
    </div>
  </div>
<% end %>
<hr>
<div class='container'>
  <div class='tile is-ancestor post-flex'>
    <% @posts.each do |post| %>
      <div class='box tile is-parent is-4 post-box mb-1'>
        <div class='tile is-child '>
          <%= link_to post do %>
            <p class='title is-5 has-text-centered'><%= post.title %></p>
            <br>
            <p><%= truncate(post.body, length: 24) %></p>
            <br>
            <% if user_signed_in? %>
              <p><strong>Author:</strong> <%= post.user.username %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class='level'>
  <h1 class='title level-item is-centered'>New Post</h1>
</div>
<%= render 'form', post: @post %>
<div class='level'>
  <%= link_to 'Back', posts_path, class: 'level-item' %>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<section class='section'>
  <div class='columns is-centered'>
    <div class='column is-one-third'>
      <h2 class='title is-4'><%= @post.title %></h2>
      <br>
      <div class='card'>
        <p class='card-content post-box'>
          <%= @post.body %>
        </p>
      </div>
      <br>
      <% if user_signed_in? %>
        <p>
          <strong>Posted by:</strong>
          <br>
          <em><%= @post.user.username %></em>
        </p>
      <% end %>
      <br>
      <%= link_to 'Back', posts_path %>
    </div>
  </div>
</section>